### ISSUE TITLE
Missing municipalities in Brazil

### ISSUE THREAD

**Issue by cndesantana** [abjur/abjData#2]
When you run the command: 

` ` ` pnud_muni %>% filter(ano == 2010) %>% select(municipio) %>% count()` ` ` 

you get to know that there are 5565 municipalities in the pnud database. 

However, it is known that there are 5570 municipalities in Brazil. 

I guess there are some missing municipalities in pnud database. However I still am not sure which ones are missing.

**Comment by cndesantana** [comment]
Here the link for a wikipedia with the list of 5570 municipalities https://pt.wikipedia.org/wiki/Lista_de_munic%C3%ADpios_do_Brasil_por_popula%C3%A7%C3%A3o

**Comment by jtrecenti** [comment]
These 5 municipalities were created after 2010

https://oglobo.globo.com/brasil/com-5-novos-municipios-brasil-agora-tem-5570-cidades-7235803

Pescaria Brava - SC 
Balneário Rincão - SC
Mojuí dos Campos - PA
Pinto Bandeira - RS
Paraíso das Águas - MS

**Comment by cndesantana** [comment]
cool!! Thanks for clarifying it!
