### ISSUE TITLE
Objeto br_uf_map ausente na nova versão

### ISSUE THREAD

**Issue by felipeangelimvieira** [abjur/abjData#4]
Olá, tudo bem?
Primeiro eu queria agradecer pelo pacote que vocês disponibilizam. Tem sido de grande ajuda.

Um dos objetos que utilizamos é o br_uf_map, que parece ausente nessa nova versão. É possível ainda ter acesso a ele de alguma forma? Ele teria trocado de nome?

**Comment by jtrecenti** [comment]
Olá @felipeangelimvieira , tudo bem?

Nós removemos o `br_uf_map` pois atualmente temos alternativas superiores que utilizam o pacote `{sf}` no backend.

Por exemplo, o pacote [`{geobr}`](https://github.com/ipeaGIT/geobr) possui a função `geobr::read_state()`, que baixa os shapes dos estados diretamente do IBGE e em formato mais amigável para plotar.

Se ainda assim precisar do objeto `br_uf_map` (por questões de compatibilidade, por exemplo), podemos anexar aqui.

**Comment by felipeangelimvieira** [comment]
Oi @jtrecenti, tudo certo.
Obrigado pela sugestão, vou usar o pacote geobr :)
