### ISSUE TITLE
Espaço na sigla na base pnud_siglas

### ISSUE THREAD

**Issue by beatrizmilz** [abjur/abjData#7]
Oi ! estava tentando gerar um arquivo de siglas para a  `pnud_min`, e percebi que tem uma sigla com um espaço extra. Arrumei com um case_when simples mas caso queiram alterar no pacote, é na base abjData::pnud_siglas, coluna `sigla`, e a sigla que contém um espaço extra é a `idhm_ e`.

Ex:
```
abjData::pnud_siglas |>
  mutate(
    sigla = case_when(
      sigla == "idhm_ e" ~ "idhm_e",      
      TRUE ~ sigla
    )
  ) |>
  filter(sigla %in% names(abjData::pnud_min))
  ```

**Comment by katerine-dev** [comment]
thanks
